import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:go_router/go_router.dart';
import '../../data/models/note_model.dart';
import '../../data/repositories/note_repository.dart';

class AddNoteScreen extends StatelessWidget {
  final TextEditingController titleController = TextEditingController();
  final TextEditingController descriptionController = TextEditingController();
  final NoteRepository noteRepository = NoteRepository();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Add Note')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            TextFormField(
              controller: titleController,
              decoration: InputDecoration(labelText: 'Title'),
            ),
            SizedBox(height: 16),
            TextFormField(
              controller: descriptionController,
              decoration: InputDecoration(labelText: 'Description'),
              maxLines: 5,
            ),
            SizedBox(height: 24),
            ElevatedButton(
              onPressed: () => _addNote(),
              child: Text('Save Note'),
            ),
          ],
        ),
      ),
    );
  }

  void _addNote() async {
    final title = titleController.text.trim();
    final description = descriptionController.text.trim();

    if (title.isEmpty || description.isEmpty) {
      Get.snackbar('Error', 'Please fill all fields');
      return;
    }

    try {
      final newNote = Note(
        id: '', // ID will be generated by Firestore
        title: title,
        description: description,
      );

      await noteRepository.addNote(newNote);
      Get.snackbar('Success', 'Note added successfully');

      // Navigate back to the home screen after saving the note
      Get.back();
    } catch (e) {
      Get.snackbar('Error', e.toString());
    }
  }
}
